### ISSUE TITLE
Make sure all models declared before configure_mappers() runs

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/marshmallow-sqlalchemy#191]
My app is still relatively small, and I had models and schemas in the same file per entity, e.g.

```
# app/models/user.py

class User(Model):
    # some model stuff

class UserSchema(ModelSchema):
    class Meta:
        model = User
        # some schema stuff
```

This caused problems with relationships, as `sqlalchemy.orm.configure_mappers()` would run too early (before all `Models` were declared). Even string names didn't work.

My solution was two-fold (thanks to ms7821 on IRC):

1. Move the `Schema` classes into different files under `app/schemas/*.py`.
2. Make sure all `Models` were instantiated by adding `from .somemodel import Somemodel` lines into `app/models/__init__.py`.

The need to make sure all models are declared is implicit in the docs:

> Declare your models
> ...
> Generate marshmallow schemas

but it caught me out for a while. Would a doc PR clarifying this be welcome?

**Comment by sloria** [comment]
Sure, I'd review a PR for docs.

**Comment by ThiefMaster** [comment]
Is there any chance marshmallow-sqlalchemy could do its job *without* analyzing models at schema import/definition time, and rather do so the first time a schema gets instantiated?

Because especially larger applications with LOTS of models spread over different parts of the app (`myapp/modules/xxx/models/yyy.py`) that make use of `relationship('ModelAsString')` for lazy dependencies (resolved only when `configure_mappers` runs), having model-backed schemas can very easily break things.

**Comment by ThiefMaster** [comment]
@sloria ping :) 

What I mentioned in my last comment is still a problem, and AFAICT marshmallow-sqalchemy doesn't actually need relationships to be fully initialized. Not sure if this is something that can be changed here or would requier changes in sqlalchemy itself (e.g. some way to allow partial initialization while skipping things that are not ready *yet*)
