### ISSUE TITLE
Why doesn't SQLAlechemySchema inherit from ModelSchema, rather than Schema?

### ISSUE THREAD

**Issue by skinofstars** [marshmallow-code/marshmallow-sqlalchemy#297]
Not sure this is an issue with the library, but it's certainly an issue for myself as a new user. I'd been trying for some time to figure how to update an existing instance. 

I could in various places that I needed to add an instance `schema.load(data, instance=Model.query.get(1))`, but it took me a long time to realise that my schema def needed to inherit from a ModelSchema and not an SQLAlchemySchema. 

Why wouldn't the SQLAlchemySchema inherit from ModelSchema rather than just Schema? And even if there is a reasonable reason for this (which I'm sure there is), shouldn't it be clearer in the docs how one might update an existing instance? 

Feel free to close this as a non-bug, I think I'm just hoping to get some understanding. Thanks.

**Comment by sloria** [comment]
`SQLAlchemySchema` is a generalization of  `ModelSchema` (and `TableSchema`) rather than a type of `ModelSchema`. It uses a different API for auto-generating fields (`auto_field`) than the older `[Model|Table]Schema`.

As for updating instances: I'd recommend doing update logic outside of marshmallow. Deserialize the data with marshmallow, then update your models with the deserialized data. At work, we use Flask-RESTy, which simply does `setattr(instance, key, value)` with the deserialized data: https://github.com/4Catalyzer/flask-resty/blob/e22faa0504a1903109f2e222b939aee0a3a55234/flask_resty/view.py#L841-L842

Hope that helps. Closing for now, but feel free to continue discussion here
