### ISSUE TITLE
Schema.dump refreshing expunged object

### ISSUE THREAD

**Issue by kaldown** [marshmallow-code/marshmallow-sqlalchemy#365]
enable SQLAlogging
```
user = User.query.first()
db.session.expunge(user)
UserSchema().dump(user)
...
2021-02-05 18:31:48,622 INFO sqlalchemy.engine.base.Engine SELECT "user".id AS user_id, .......
```

What to do in order to prevent Schema refreshing of an expunged instance?

**Comment by peterschutt** [comment]
Hey, can you provide a minimal example of this that I can run to verify? 

I cannot see how the library would add an expunged instance back into the session on dump. In fact, from what I can see, this library doesn't seem to override `Schema.dump()`, so that should just be pure marshmallow code which knows nothing of sqlalchemy sessions.

**Comment by sloria** [comment]
closing for now as this has gone stale. please comment though if it's still an issue!
